#ifndef __MAIN_H__
#define __MAIN_H__
#include"INTRINS.H"
#include"STC12C5A60S2.H"
#include"STC12C5A60S2_PWM.H"
#include"STC12C5A60S2_UART.H"
#include"STC12C5A60S2_ADC.H"
#include"STC12C5A60S2_TIME.H"
//#include"STC12C5A60S2_WAIADC.H"
#include"DS18B20.H"
#include"Key4x4.H"
#include"SEGx8.H"
#include"DELAY.H"
#include"Step_Motor.H"
#include"T1_Count.H"
#include"LCD12864.H"
#include"SYN6288.H"
#include"DS1302.H"
#include"SuperVoice.H"
#include"HX711.H"


// Ctrl + C ¸´ÖÆ
// Ctrl + X ¼ôÇÐ
// Ctrl + V Õ³Ìù
// Ctrl + Z ³·Ïú
// Ctrl + F ²éÕÒ
// Ctrl + H Ìæ»»

#endif